# Generated by Django 5.2.6 on 2025-09-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingxiapp', '0002_emotiondiary'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotiondiary',
            name='emotion_score',
            field=models.FloatField(default=0.0),
        ),
    ]
